version: '3.8'
services:
  frontend:
    container_name: cellrex-frontend
    build: ./frontend
    # user: "${UID}:${GID}"
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ${LOCAL_PATH_DATA}:/appfe/data
      - ${LOCAL_PATH_UPLOAD}:/appfe/upload
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
      - cellrex-network

  backend:
    container_name: cellrex-backend
    build: ./backend
    # user: "${UID}:${GID}"
    ports:
      - 8000:8000
    environment:
      - DATABASE_BACKEND=sqlite #${DATABASE_BACKEND}
      - DATABASE_BACKEND_SQLITE_FILE=sqlite/CellRexMetadata.sqlite
    volumes:
      - ${LOCAL_PATH_DATA}:/appbe/data
      - ${LOCAL_PATH_UPLOAD}:/appbe/upload
      - ${LOCAL_PATH_CONFIG}:/appbe/config
      - ${LOCAL_PATH_PROTOCOLS}:/appbe/protocols
      - ${LOCAL_PATH_SQLITE}:/appbe/sqlite # must not be stored on a distributed file system
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
      - cellrex-network

networks:
  cellrex-network:
    driver: bridge
